[package]
name = "simplex-s3"
version = "0.9.0"
description = "AWS S3 client for Simplex"

[dependencies]
simplex-std = { path = "../simplex-std" }
simplex-http = { path = "../simplex-http" }
simplex-json = { path = "../simplex-json" }
