[package]
name = "simplex-ses"
version = "0.9.0"
description = "AWS SES email client for Simplex"

[dependencies]
simplex-std = { path = "../simplex-std" }
simplex-http = { path = "../simplex-http" }
simplex-json = { path = "../simplex-json" }
